export enum TodoActionType {
    'ADD_TODO' = 'ADD_TODO',
    'UPDATE_TODO_STATUS' = 'UPDATE_TODO_STATUS',
    'UPDATE_ALL_TODO_STATUS' = 'UPDATE_ALL_TODO_STATUS',
    'DELETE_TODO' = "DELETE_TODO",
    'DELETE_DONE_TODOS' = 'DELETE_DONE_TODOS'
}